jobs:
  include:
  - stage: build
    language: java
    dist: bionic
    script:
    - mvn clean install -DskipTests -B
  - stage: unit-test
    services: mysql
    language: java
    dist: bionic
    script: mvn test -B
  - stage: integration-test
    services:
    - mysql
    language: java
    dist: bionic
    script: mvn verify -DskipUTs=true -B
stages:
- build
- unit-test
- integration-test
- name: deploy
  if: branch IN (master, dev) AND type = push
