language: java
dist: trusty
jobs:
  include:
  - stage: build
    script:
    - mvn clean install -DskipTests -B
  - stage: unit-test
    services: mysql
    script: mvn test -B
  - stage: integration-test
    services: mysql
    script: mvn verify -DskipUTs=true -B
stages:
- build
- unit-test
- integration-test
- name: deploy
  if: branch IN (master, dev) AND type = push
  
addons:
  sonarcloud:
    organization: "etnoy"
    token:
      secure: "CHoleb1JR6c68y3Yt4qn29G2HLPc57opML/Lyj5130oo34s8A3J4/FQ1ppNeSCeaeHuWS6VLakOUUcCHVqumsdPEIJZXnblZzYeRd6VpKJCm+MMXZ1Z/GjJVHs0f03kfMJB+J228VtePKh0+syHbsmyxylm8GgnxSQ4B6w7OvZFT+ehiGn+YHCRAxfdE8RNive0H7cQ4xijE9lAzQBTkJXqFYQ8N0D+fIHlgL2A9AiA1lHr0lie/JEYzGWf7fkLsgM3Mg1VOmSHw5PfdFN9zOJLMN25QfoZ1WNhefKzdbho5g2PrxQK/DksDNvfC+41uYOFq9DrIKntvjPZipGLZdi3vd8UNL69l49Cu7io+Na/OvL5Uzu77DcCfIU3YwWzwYRzRoDBAppFg+t2bBU9UuJ2DfQo0dz4mTykHLc8HmYtjF8pUM9YUOYabkAFMqxK8zSTBl0Erb8PGLlzZIXacGAPnizIEaEuC0KAa92xZDU3noC1s2xRgvZdelqtK8IkjuMAflvw7wvJ2OR9/eCFsLRB5lKzVeLICCeqhHOO5OCSjWvPU8OMqlF1vWrjKtesg8KPeEp0Ea17Q9NUDxQ6Je6VyKlBzfWgqUIjHbCsVR8s53WNnaOIkUFdgQrEywvz7ObrdiS597xkDin+qjR6WMPlQ30dWTZpA6lGzlYC1t3Q="    
      
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=etnoy_SecurityShepherd