language: java

jobs:
  include:
  - stage: build
    script: 
    - cd server
    - mvn clean install -DskipTests -B
  - stage: unit-test
    services: mysql
    script: 
    - cd server
    - git fetch --unshallow
    - mysql -e 'CREATE DATABASE IF NOT EXISTS core;'  
    - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=etnoy_SecurityShepherd -B
  - stage: integration-test
    services: mysql
    script:
    - cd server
    - mysql -e 'CREATE DATABASE IF NOT EXISTS core;'  
    - mvn verify -DskipUTs=true -B
    
stages:
- build
- unit-test
- integration-test
- name: deploy
  if: branch IN (master, dev) AND type = push
  
addons:
  sonarcloud:
    organization: "etnoy"
    token:
      secure: "bt8lgRbINrjx+UsckDjpiy65yDImXdeL8UP3Jz7AQrBVr+xrdZwXeo0MxLJqkljj2OYlh9gF83n9g2zN83fqGsD8DUlh9T7c9hofD7owXGdm+Mrlke8uq/SQyg5npGHxnh/Oelz6M/ZF2saOgQITwIovtrVt7nOWiG/3pj9TeJleQgHTdp/RiGktg5YeWM64vDh1MxYs/jMLPbjGGsIvkR42ZaTD6zPVfTHubs5G9Oz5uI/WWsmp+FQ72Be9saDju22Sc2pfAWO8Gaaef4vgHTVpuiqqcZNvGxEwS6JCFkv9pXhGg4UBrCD8Tjg/V3ejJeQHsGcgMhuul+0BWZzqgX+JE9E2VJQe+1OD34OCueR5JWASyNts9J7tk221oF6B5/rA/mEdIJzUFVpcedqqbh8tPgKuH3ySmDYbuUSKVcPRe+SZ/o5vd2KgGNZ8uog1LlKnRlPliySq1wvmw6mmHuPrw5uzRj3R3MXFbshk9dtUYhp47Yb3V26qmxAGOP5PisB1GHZa/smsfm+Yq4l/N+6MujNC+ZHio+gsDqOiJs/8dmcRMCjE++rBgrbj7fkRhjWH6Cd4i+jVqAi0Kij42hKklRwxjgMAUYfZQGFw78bWJV5NHDBwQTDmiqwhNCMeRRms+ySnRwDjWw3AMrwsUBDEiRHJrHnQV2OX1VSqwik="
