language: java
jobs:
  include:
  - stage: build
    script:
    - mvn clean install -DskipTests -B
  - stage: unit-test
    services: mysql
    script: mvn test -B
  - stage: integration-test
    services: mysql
    script: mvn verify -DskipUTs=true -B
stages:
- build
- unit-test
- integration-test
- name: deploy
  if: branch IN (master, dev) AND type = push
addons:
  sonarcloud:
    organization: "etnoy"
    token:
      secure: "tI4HxQzKnZjz4Ku3sPCoSs2Iii3sU8hN3O6W8AEQmIlgDrrsXOQ2fK4keI69URFk1SapRNfpQhXwPp2ynKD9pw/gvElsZg2trX3jr7wyFsdXRYn3CcY7lebVMQwXxeRhM5dBP9yMn3NPSoSD2bMQ6sC5BzU8vyVuutIXQsqyPWPIsUSMoQOPnLVJEM22D9KhUOnqTvi3mKPu9hdx7lD2kszFypiBu5VS77Cw0UjDWjiD2N0rxYQOf3uWX+oJiyAeEsBS0LaBtUPzVsbmuf4r1aIStdHGph4Ch6v5LFHB+FC2m8ZCAcZeMpDvEa7eW7bgMu2RwwZQ7sqKOSxSkQog1bFn6i7kMAh1NVMXnwciPjDs/RVf2g11YAQQyLCNXIk1HpVnt7xCqui+paJ7o1faWD4DJkZ0wCDyp8qLfgommiIPIK+HTKM5QuzFpAc83shsbim4kniewBhWmu3LlMlEB+PWYR2ILVPLUEFP17j5fp+sNtNWVpOun9BsrQKWplYJQfP+zXpyGEUAmWNiuh1Jshil3roKMLax+Wpe4O1SxTTra9uuoX9FRfgpq7JTdyChCvM82QVEaFarq2o5HpHLfnQCHXdxo6LY7RRRLdcpmkPHCDG1rVmvzBiW+ueL9VyahFxEZ61H4fYNk5kWp7JPhOq6ZGNwjzXX0hs2SQdU2Uo="
script:
  - sonar-scanner
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=etnoy_SecurityShepherd