language: java
jobs:
  include:
  - stage: build
    script:
    - mvn clean install -DskipTests -B
  - stage: unit-test
    services: mysql
    script: mvn test -B
  - stage: integration-test
    services: mysql
    script: mvn verify -DskipUTs=true -B
stages:
- build
- unit-test
- integration-test
- name: deploy
  if: branch IN (master, dev) AND type = push
addons:
  sonarcloud:
    organization: "etnoy"
    token:
      secure: "ImqWktnOtUy7pD0LpCc5ZWAB1gUc7V7e5UERri12NaZxlmGqZkwmkDLCwn5rFF+lDwugmMYkNi/RLAcLtj99B62qDYqvSV87LwR8/QGl0VS7MPYHEM+gDxkfp+l9iqtkv05jNhGvRoJdpSC4ocC6CuSHOeD0yppwG7wTQC9BctBtp9jlyUN4On227OBTUDO0W9QFzxtKOqjyYK+bO00vdbwGGL/EQoWfwz6RZFh+WNmBFtue71nDccyKe1v46kwmDmYYDIpKchxF4bOQDdPAQDDoxkvKCLrOcU3HRMpVMWzkqgCCBPNT3c32Yi53Q963P+ftwjDIKaUwNLP79Ljv1ZyIkyCWRT2wK1oR7KkgG3MOZQbpIrce1t3Q45eU3XG/+6FbLbJ3Rtig4uE9pJ6n7Wokszytml020zMF/LcIxdafLt7nAWhbE1so7bkmhDQ6IPGtM5jk14q+p3zBPI7ITczkZTueh8oA+HFhzqipuCLIwtKJ/rG6FX0THMinxhCE2hZiNnEpRkF9NQTqz2AYfXDEmRMcizOAOhaNH7KAj44FDNUfGC4Ksr1i3dmM+roLqRWkMgsZL9vSozXgaJ0xz8H1GiczmeHDeagXIeUVVmVVDtOmmvAgDPajnxbdHe3gg35xyc9qU7+j4oawygImZqj+SoChpXo1kB0PLuLjOqE="
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=etnoy_SecurityShepherd