INSERT INTO `user` VALUES (1,'Test User',NULL,NULL,NULL);
INSERT INTO `auth` VALUES (1,0,0,1,NULL,NULL,NULL,NULL,1);
INSERT INTO `password_auth` VALUES (1,'test','$2y$12$b8R5cdzNZOS38qxxigp9EueR4oUF44xlPYqdpNWnHf3WCNffXZK0m',1);